apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv5
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /srv/nfs/storage/pv5
    server: support1.861b.internal 
  persistentVolumeReclaimPolicy: Recycle 

